Added news list at the frontpage and changed the images to all members
radical-group/radical-group.github.io pull request #22
Opened 2018-11-06 14:39 UTC by iparask

Fixes #6 , fixes #5 , fixes #21

2018-11-14 20:39 UTC, mturilli approved these changes

2018-11-26 13:37 UTC, iparask commented
Hello @shantenujha, @vivek-bala. Unless you finish the review of this PR it cannot be merged. This blocks a lot of other issues ad PRs

2018-11-26 16:00 UTC, vivek-bala approved these changes

2018-11-27 22:20 UTC, mturilli requested changes
As discussed, I would move to a double column format with Name and title.

2018-11-30 21:16 UTC, mturilli approved these changes
Seems good to go to me!

2018-11-30 21:23 UTC, merged